/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    screens: {
      sm: "0px",
      md: "600px",
      lg: "900px",
      xl: "1200px",
      "2xl": "1536px",
    },
    colors: {
      green: "#6eb072",
      red: "#f65c5c",
      darkGrey: "#25263e",
      primaryMain: "#00A8A3",
      primaryDark: "#007E7A",
      drawerColor: "#252935",
      white: "#fff",
      black: "#000",
      riverBed: "#4D4F5C",
      santaGrey: "#a1a0ae",
      magnolia: "#f5f6fa",
      porcelain: "#f2f2f2",
      platinum: "#e4e4e4",
      ashGrey: "#b9babf",
      aluminium: "#afafaf",
      pastelGrey: "#ccc",
      dune: "#333",
      mercury: "#e6e6e6",
      silverChalice: "#adadad",
      jungleGreen: "#212529",
      mountainMist: "#949494",
      smokeyGrey: "#706e6e",
      whiteIce: "#dff9ed",
    },
    fontFamily: [
      "circular",
      "-apple-system",
      "BlinkMacSystemFon",
      "Segoe UI",
      "Roboto",
      "Oxygen",
      "Ubuntu",
      "Cantarell",
      "Fira Sans",
      "Droid Sans",
      "Helvetica Neue",
      "sans-serif",
    ],
    extend: {
      drawer: {},
    },
  },
  important: "#root",
  plugins: [],
  corePlugins: {
    preflight: false,
  },
};
